create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  user_id uuid references auth.users(id) on delete set null,
  session_id text not null,
  properties jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint analytics_events_event_name_check check (
    event_name in (
      'app_opened',
      'oauth_started',
      'state_synced',
      'account_deleted'
    )
  ),
  constraint analytics_events_session_id_check check (
    char_length(session_id) between 8 and 160
  )
);

alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from anon, authenticated;
grant insert (event_name, user_id, session_id, properties)
  on table public.analytics_events to anon, authenticated;
grant usage, select on sequence public.analytics_events_id_seq
  to anon, authenticated;

drop policy if exists "Clients can submit safe analytics events"
  on public.analytics_events;
create policy "Clients can submit safe analytics events"
  on public.analytics_events
  for insert
  to anon, authenticated
  with check (
    (user_id is null and (select auth.uid()) is null)
    or (select auth.uid()) = user_id
  );

create index if not exists analytics_events_name_occurred_at_idx
  on public.analytics_events (event_name, occurred_at desc);

comment on table public.analytics_events is
  'Optional minimal product-learning events. Do not store free text or sensitive data.';
